import {
  AttributeType,
  ModifierType,
} from '@shared/engine/battle-v5/core/types';
import type { SectDefinitionWithoutPaths } from '../../core';
import { JIUJIE_CALAMITY, JIUJIE_SECT_ID } from './ids';

const effects = { damage: 0.14, heal: 0.12, shield: 0.14, status: 0.2 };
const durationMilestones = [
  { level: 60, bonus: 1 },
  { level: 120, bonus: 2 },
];

export const JIUJIE_BASE_DEFINITION: SectDefinitionWithoutPaths = {
  id: JIUJIE_SECT_ID,
  name: '九劫天宫',
  description:
    '九劫天宫奉天听而执劫簿，以不可驱散的劫雷记录出手，以劫债等待天道清算。',
  raceIds: ['human'],
  configVersion: 1,
  foundationPassiveId: 'jiujie-tianwei-runtime',
  combatResource: { id: JIUJIE_CALAMITY, name: '劫数', icon: '⚡', max: 3 },
  methods: [
    {
      id: 'jiujie-canon',
      slot: 1,
      name: '《九劫天书》',
      isPrimary: true,
      description: '总录九劫法度，执雷而不滥刑。',
      growthProfile: { curve: 'balanced', effects, durationMilestones },
    },
    {
      id: 'calamity-eye',
      slot: 2,
      name: '《劫眼观世》',
      description: '以身为劫眼，观来力而承其灾。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAX_HP,
          type: ModifierType.ADD,
          maxValue: 0.12,
        },
      },
    },
    {
      id: 'heavenly-record',
      slot: 3,
      name: '《天谴录》',
      description: '以天听辨行为，以劫簿记主罪。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_ATK,
          type: ModifierType.ADD,
          maxValue: 0.15,
        },
      },
    },
    {
      id: 'thunder-prison',
      slot: 4,
      name: '《雷狱镇魂》',
      description: '雷狱穿透护持，使天罚不为法障所蔽。',
      growthProfile: {
        curve: 'balanced',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_PENETRATION,
          type: ModifierType.FIXED,
          maxValue: 0.08,
        },
      },
    },
    {
      id: 'cause-judgment',
      slot: 5,
      name: '《因果问罪》',
      description: '问因果、收劫债，留足清算天威。',
      growthProfile: {
        curve: 'balanced',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAX_MP,
          type: ModifierType.ADD,
          maxValue: 0.18,
        },
      },
    },
    {
      id: 'crossing-calamity',
      slot: 6,
      name: '《渡劫归真》',
      description: '渡劫之后仍守法身，不以天威伤己。',
      growthProfile: {
        curve: 'early',
        effects,
        durationMilestones,
        panelModifier: {
          attrType: AttributeType.MAGIC_DEF,
          type: ModifierType.ADD,
          maxValue: 0.14,
        },
      },
    },
  ],
  abilities: [
    {
      id: 'thunder-finger',
      kind: 'default',
      baseName: '惊雷指',
      description: '仅在主动神通均不可用时使用，以雷力造成基础伤害。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 1 },
      mpCost: 0,
      cooldown: 0,
    },
    {
      id: 'heaven-hearing',
      kind: 'active',
      baseName: '天听引雷',
      description: '造成0.55倍法攻雷伤，并在目标身上留下不可驱散的劫雷。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 1 },
      mpCost: 80,
      cooldown: 0,
    },
    {
      id: 'receive-calamity',
      kind: 'active',
      baseName: '承天受劫',
      description: '暂承来力，将受过的灾厄记入劫簿。',
      role: 'defensive',
      unlock: { type: 'method', methodId: 'calamity-eye', level: 1 },
      mpCost: 120,
      cooldown: 4,
    },
    {
      id: 'calamity-seal',
      kind: 'active',
      baseName: '劫簿落印',
      description: '造成0.25倍法攻雷伤并落印；目标已有劫雷时，额外增加一层劫债。',
      role: 'generator',
      unlock: { type: 'method', methodId: 'heavenly-record', level: 1 },
      mpCost: 120,
      cooldown: 2,
    },
    {
      id: 'thunder-prison-question',
      kind: 'active',
      baseName: '雷狱问行',
      description: '造成0.65倍法攻雷伤，追问目标仍在劫中的下一步并推进天罚。',
      role: 'combo',
      unlock: { type: 'method', methodId: 'thunder-prison', level: 1 },
      mpCost: 140,
      cooldown: 2,
    },
    {
      id: 'borrow-calamity',
      kind: 'active',
      baseName: '借劫回身',
      description: '消耗一分劫数，获得相当于最大气血15%的护盾。',
      role: 'defensive',
      unlock: { type: 'method', methodId: 'crossing-calamity', level: 1 },
      mpCost: 100,
      cooldown: 3,
    },
    {
      id: 'causal-echo',
      kind: 'active',
      baseName: '因果回响',
      description: '造成0.45倍法攻的基础雷伤，并根据劫债追加伤害。',
      role: 'utility',
      unlock: { type: 'method', methodId: 'cause-judgment', level: 5 },
      mpCost: 140,
      cooldown: 3,
    },
    {
      id: 'nine-sky-settlement',
      kind: 'active',
      baseName: '九霄清算',
      description: '以劫数为引，清算目标累积的劫债。',
      role: 'finisher',
      unlock: { type: 'method', methodId: 'jiujie-canon', level: 10 },
      mpCost: 200,
      cooldown: 5,
    },
    {
      id: 'jiujie-tianwei-runtime',
      kind: 'passive',
      baseName: '天威裁决',
      description:
        '天宫弟子受到敌方主动法术或负面技能时，有20%的几率免疫整个技能。',
      role: 'defensive',
      unlock: { type: 'always' },
      sourceMethodId: 'heavenly-record',
    },
    {
      id: 'jiujie-law-runtime',
      kind: 'passive',
      baseName: '劫律运行',
      description: '记录劫雷触发与天宫劫簿。',
      role: 'utility',
      unlock: { type: 'always' },
      sourceMethodId: 'jiujie-canon',
      visibility: 'internal',
    },
  ],
  onboarding: {
    initialContribution: 30,
    initialMethods: {
      'jiujie-canon': 5,
      'calamity-eye': 1,
      'heavenly-record': 1,
      'thunder-prison': 1,
      'cause-judgment': 1,
      'crossing-calamity': 1,
    },
    initialAbilityLoadout: ['heaven-hearing', 'calamity-seal', null, null],
  },
};
